source 'https://rubygems.org'
gem 'sensu', '~> 1.2', '>= 1.2.1'
gem 'sensu-plugins-disk-checks', '~> 2.5', '>= 2.5.1'
gem 'sensu-plugins-process-checks', '~> 2.7'
gem 'sensu-plugins-vmstats', '~> 1.0'
gem 'sensu-plugins-load-checks', '~> 4.0'
gem 'sensu-plugins-http', '~> 2.6'
gem 'sensu-plugins-ssl', '~> 1.5'
gem 'sensu-plugins-filesystem-checks', '~> 1.0'
gem 'sensu-plugins-uchiwa', '~> 1.0'
gem 'sensu-plugins-network-checks', '~> 2.3'
gem 'sensu-plugins-mysql', '~> 2.2', '>= 2.2.1'
gem 'sensu-plugins-redis', '~> 2.3', '>= 2.3.2'
gem 'sensu-plugins-io-checks', '~> 1.0', '>= 1.0.1'
gem 'sensu-plugins-apache', '~> 2.0'
